const $=id=>document.getElementById(id);
const tabs={assembly:{name:'Сборка',title:'Сборка заказов',icon:'▣',desc:'Сканируйте товар. Сразу видите результат. Продолжайте сборку.',steps:[['Выберите поставку','Открытая поставка WB остаётся выбранной на весь сеанс.'],['Нажмите кнопку сканера','Не нужно касаться поля ввода или закрывать клавиатуру.'],['Проверьте результат','Товар, размер, ячейка и подтверждение на одном экране.']]},receiving:{name:'Приёмка',title:'Приёмка товара',icon:'⇣',desc:'Сначала коробка. Затем товары. Терминал ведёт по шагам.',steps:[['Выберите зону','Офис или склад №2 — приёмка всегда в выбранную зону.'],['Сканируйте коробку','QR-код задаёт место хранения для следующих товаров.'],['Принимайте товары','Каждый скан добавляет одну штуку. Завершите сеанс кнопкой.']]},cells:{name:'Ячейки',title:'Ячейки и поиск',icon:'▦',desc:'Найдите нужный товар и сразу увидите, где он хранится.',steps:[['Сканируйте товар','Физическая кнопка запускает поиск по штрихкоду.'],['Получите адрес','Зона, номер коробки и остаток в одной карточке.'],['Откройте ячейку','Посмотрите содержимое или подготовьте её QR-код.']]},more:{name:'Ещё',title:'Все возможности',icon:'☰',desc:'Отчёты, настройки и управление складом доступны на терминале.',steps:[['Откройте нужный раздел','Дополнительные функции собраны в отдельном меню.'],['Выберите действие','Ячейки, QR-коды, отчёты и настройки.'],['Вернитесь к работе','Основные операции всегда доступны в нижней навигации.']]}};
let state;const base=()=>({tab:'assembly',count:12,received:0,box:false,zone:'Офис',result:null,events:[],modal:null,manual:'',offline:false,supply:'07.10.2026',undo:false});state=base();
function event(text,type='ok'){state.events.unshift({text,type,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})});state.events=state.events.slice(0,6);}
function button(text,action,extra=''){return `<button class="app-button ${extra}" data-action="${action}">${text}</button>`;}
function scanReady(text,sub){return `<div class="scan-ready"><div class="barcode" aria-hidden="true">▥</div><strong>${text}</strong><p>${sub}</p></div>`;}
function setTab(tab){if(!tabs[tab])return;state.tab=tab;state.modal=null;state.result=null;render();}
function scan(kind='normal'){
 if(state.modal==='manual'){if(kind!=='normal')return;applyManual();return;}
 if(state.modal)return;
 if(state.tab==='more'){state.result={type:'info',title:'Выберите рабочий раздел',text:'Сканирование доступно в сборке, приёмке и поиске.'};render();return;}
 if(state.offline){state.result={type:'error',title:'Нет связи',text:'Операция не записана. Восстановите связь и повторите сканирование.'};event('Нет связи · операция не выполнена','error');render();return;}
 if(kind==='unknown'){state.result={type:'error',title:'Товар не найден',text:'Проверьте штрихкод или справочник. Остатки не изменены.'};event('Неизвестный штрихкод','error');render();return;}
 if(kind==='repeat'&&state.tab==='assembly'){state.result={type:'error',title:'Заказ уже собран',text:'Этот заказ не добавлен повторно. Проверьте следующий заказ.'};event('Повтор · заказ уже собран','error');render();return;}
 if(state.tab==='assembly'){
  if(state.count>=48){state.result={type:'info',title:'Поставка собрана',text:'Все 48 заказов уже собраны в этом примере.'};render();return;}
  state.count++;state.undo=true;state.result={type:'ok',title:'Товар добавлен',text:'Костюм бежевый · 52–56 · BOX-0002',code:'2041541853067'};event('Сборка · +1 заказ');
 }else if(state.tab==='receiving'){
  if(!state.box){state.box=true;state.result={type:'ok',title:'BOX-0002 открыта',text:'Теперь сканируйте товары для приёмки.'};event('Выбрана коробка · '+state.zone);}
  else{state.received++;state.result={type:'ok',title:'Товар принят',text:'Добавлена 1 шт. в BOX-0002 · '+state.zone};event('Приёмка · +1 шт.');}
 }else{state.result={type:'ok',title:'Товар найден',text:'Офис · BOX-0002 · Остаток 25 шт.',code:'2041541853067'};event('Поиск · найдена BOX-0002');}
 render();
}
function showModal(name){state.modal=name;state.manual='';render();}
function applyManual(){if(!state.manual.trim())return;const code=state.manual.trim();state.modal=null;if(code==='2041541853067'||code==='BOX-0002')scan();else scan('unknown');}
function screen(){
 const r=state.result;let message=r?`<div class="app-result ${r.type==='error'?'error':''}" role="status">${r.type==='ok'?'✓':'!'} ${r.title}</div>`:'';
 if(state.tab==='assembly')return `<h2>Сборка</h2><div class="app-card"><div class="app-row"><span class="muted">Поставка · ${state.supply}</span><strong>${state.count} / 48</strong></div><div class="app-progress"><span style="width:${state.count/48*100}%"></span></div></div>${message}${r?.type==='ok'?`<div class="app-card app-product"><h3>Костюм трикотажный</h3><p>Бежевый · 52–56 · 170–175</p><code>Офис · BOX-0002</code></div><div class="app-grid">${button('Этикетка','print')}${button('Отменить','undo')}</div>`:scanReady('Готов к сканированию','Нажмите жёлтую кнопку ТСД')}<div class="app-grid">${button('Ввести вручную','manual')}${button('История','history')}</div>${r?'<p class="muted">Сканер готов к следующему товару</p>':''}`;
 if(state.tab==='receiving')return `<h2>Приёмка</h2><div class="app-grid">${button('Офис','office',state.zone==='Офис'?'zone-selected':'')}${button('Склад №2','warehouse',state.zone==='Склад №2'?'zone-selected':'')}</div><div class="app-card"><p class="muted">Шаг ${state.box?2:1} из 2</p><h3 style="font-size:15px;margin:8px 0">${state.box?'Товары → BOX-0002':'Сканируйте коробку'}</h3><p>${state.box?'Принято в сеансе: '+state.received+' шт.':'QR-код задаст место приёмки'}</p></div>${message}${!r?scanReady(state.box?'Сканируйте товар':'Сканируйте QR коробки','Жёлтая кнопка на терминале'):''}<div class="app-grid">${button('Ввести вручную','manual')}${button(state.box?'Завершить':'Коробки',state.box?'finish':'boxes')}</div>${button('Создать QR-коды','createbox','full')}`;
 if(state.tab==='cells')return `<h2>Ячейки и поиск</h2>${message}${r?.type==='ok'?`<div class="app-card app-product"><h3>BOX-0002 · Офис</h3><p>Костюм бежевый · 52–56</p><p style="margin-top:10px;color:#85dfb4">Хранится: 25 шт.</p><code>Добавлено 56 · изъято 31</code></div>${button('Открыть содержимое','boxdetail','full')}`:scanReady('Найти товар','Сканируйте штрихкод или QR ячейки')}<div class="app-grid">${button('Ввести вручную','manual')}${button('Коробки','boxes')}</div>${button('Создать ячейки','cells','full')}${button('Этикетки и QR зоны','labels','full')}`;
 return `<h2>Все возможности</h2><div class="app-list">${[['reports','Отчёты и Excel','Остатки · позиции · запас'],['cells','Управление ячейками','Секция · ряд · сторона · ярус'],['labels','Этикетки и QR','Коробки · ячейки · зоны'],['settings','Настройки','Пользователи · WB · справочник'],['supply','Поставки','Открытые и закрытые'],['profile','Аккаунт','Beltanee · администратор']].map(x=>button(`<strong>${x[1]}</strong><small>${x[2]}</small>`,x[0])).join('')}</div>`;
}
function modal(){let body='';const m=state.modal;
 if(m==='manual')body=`<h3>Ввести вручную</h3><label>Штрихкод или QR-код<input id="manual-input" value="${state.manual}" inputmode="none" autocomplete="off" placeholder="Код товара или коробки"></label><div class="keypad">${['1','2','3','4','5','6','7','8','9','⌫','0','C'].map(k=>`<button class="app-button" data-digit="${k}">${k}</button>`).join('')}</div>${button('Вставить код примера','sample','full')}${button('Применить','apply','primary full')}`;
 else if(m==='supply')body=`<h3>Выбор поставки</h3>${button('07.10.2026 · На сборке','selectsupply','primary full')}<button class="app-button full" disabled>06.10.2026 · Закрыта</button><p class="muted">В этом примере показаны две поставки.</p>`;
 else if(m==='boxes')body=`<h3>Коробки · ${state.zone}</h3>${button('BOX-0002 · 25 шт.','boxdetail','full')}${button('BOX-0003 · 39 шт.','boxdetail','full')}${button('Создать QR-коды','createbox','full')}`;
 else if(m==='boxdetail')body=`<h3>BOX-0002 · Офис</h3><div class="app-card"><p>Костюм трикотажный · бежевый</p><p>52–56 · 170–175</p><p style="margin-top:12px">Хранится: 25 шт.<br>Изъято: 31 шт.</p></div>${button('QR-код коробки','print','full')}${button('Переместить','move','full')}${button('Удалить коробку','delete','full')}`;
 else if(m==='cells')body=`<h3>Создать ячейки</h3><div class="app-grid"><label>Секция<select><option>Л</option><option>П</option></select></label><label>Ряд<select>${Array.from({length:8},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label><label>Сторона<select><option>Одинарный</option><option>А</option><option>Б</option></select></label><label>Ярус<select><option>Все 1–6</option>${Array.from({length:6},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label></div><label>Позиций<input type="number" value="5" min="1"></label>${button('Создать выбранное + PDF','demo','primary full')}${button('Весь склад','demo','full')}${button('Одна ячейка','demo','full')}`;
 else if(m==='createbox')body=`<h3>QR-коды коробок</h3><label>Префикс<input value="BOX"></label><label>Количество<input type="number" value="1" min="1"></label>${button('Подготовить QR-коды','demo','primary full')}`;
 else if(m==='reports')body=`<h3>Отчёты и Excel</h3><label>Зона<select><option>Офис</option><option>Склад №2</option></select></label>${button('Остатки','report','full')}${button('Отчёт по позициям','report','full')}${button('Запас','report','full')}${button('Выгрузить Excel','demo','primary full')}`;
 else if(m==='report')body=`<h3>Остатки · пример</h3><div class="app-card"><p>BOX-0002 · 25 шт.</p><p>BOX-0003 · 39 шт.</p><p class="muted" style="margin-top:10px">Показаны две примерные позиции.</p></div>${button('Выгрузить Excel','demo','full')}`;
 else if(m==='settings')body=`<h3>Настройки</h3>${button('Пользователи и роли','users','full')}${button('Токен WB','token','full')}${button('Справочник товаров','catalog','full')}${button('Печать и этикетки','labels','full')}`;
 else if(m==='users')body=`<h3>Пользователи</h3><div class="app-card">Beltanee · admin</div><label>Новый пользователь<input placeholder="Логин"></label><label>Роль<select><option>Сборщик</option><option>Администратор</option></select></label>${button('Добавить в примере','demo','full')}`;
 else if(m==='token')body=`<h3>Подключение WB</h3><p>В демонстрации токены не запрашиваются. Экран предусмотрен для будущего приложения.</p>`;
 else if(m==='catalog')body=`<h3>Справочник</h3><div class="app-card">Костюм трикотажный<p class="muted">2041541853067 · 52–56</p></div>${button('Импорт Excel · пример','demo','full')}`;
 else if(m==='labels'||m==='print')body=`<h3>Этикетки и QR</h3><label>Тип<select><option>Коробка</option><option>Ячейка</option><option>Зона</option></select></label><div class="app-card"><p>BOX-0002</p><p style="font-size:34px;letter-spacing:8px;text-align:center;margin:12px 0">▥</p><p class="muted">Условное изображение · не для сканирования</p></div><p class="muted">Печать отложена на следующий этап.</p>${button('Показать подготовку','demo','full')}`;
 else if(m==='history')body=`<h3>История операций</h3>${state.events.length?state.events.map(e=>`<div class="app-card"><p>${e.text}</p><p class="muted">${e.time}</p></div>`).join(''):'<p>Пока нет операций. Нажмите кнопку сканирования.</p>'}`;
 else if(m==='profile')body=`<h3>Beltanee</h3><p>Роль: администратор</p>${button('Сменить аккаунт · пример','demo','full')}${button('Выход · пример','demo','full')}`;
 else if(m==='delete')body=`<h3>Удалить BOX-0002?</h3><p>Подтверждение защищает от случайного нажатия.</p>${button('Подтвердить в макете','demo','full')}`;
 else if(m==='move')body=`<h3>Переместить коробку</h3><label>Зона<select><option>Офис</option><option>Склад №2</option></select></label>${button('Подтвердить в макете','demo','primary full')}`;
 return `<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-label="${m}">${body}<button class="close" data-action="close">Закрыть</button></section></div>`;
}
function render(){const t=tabs[state.tab];$('page-title').textContent=t.title;$('page-description').textContent=t.desc;$('scenario-title').textContent=state.tab==='receiving'?'Коробка, затем товары':state.tab==='cells'?'Точный адрес вместо поиска':state.tab==='more'?'Функции остаются под рукой':'От сканирования до результата';$('steps').innerHTML=t.steps.map((x,i)=>`<div class="step ${i===(state.result?2:state.box?1:0)?'active':''}"><span class="step-number">${i+1}</span><div><strong>${x[0]}</strong><p>${x[1]}</p></div></div>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===state.tab);b.setAttribute('aria-pressed',String(b.dataset.tab===state.tab));});$('screen-main').innerHTML=screen();$('app-nav').innerHTML=Object.entries(tabs).map(([k,v])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}" aria-pressed="${state.tab===k}"><span aria-hidden="true">${v.icon}</span>${v.name}</button>`).join('');$('sheet-layer').innerHTML=state.modal?modal():'';let r=state.result;$('outcome').className='outcome '+(r?.type||'');$('outcome').innerHTML=r?`<div class="outcome-symbol">${r.type==='ok'?'✓':r.type==='error'?'!':'▥'}</div><h2>${r.title}</h2><p>${r.text}</p>${r.code?`<code class="code">${r.code}</code>`:''}`:'<div class="outcome-symbol">▥</div><h2>Ожидает сканирования</h2><p>Нажмите жёлтую кнопку на терминале, чтобы пройти сценарий.</p>';$('outcome').setAttribute('aria-live','polite');$('event-count').textContent=state.events.length;$('events').innerHTML=state.events.length?state.events.map(e=>`<div class="event"><i>${e.type==='error'?'!':'✓'}</i><div>${e.text}<small>${e.time}</small></div></div>`).join(''):'<div class="event empty">Здесь появятся действия с терминала.</div>';document.querySelector('[data-test="offline"]').textContent=state.offline?'Восстановить связь':'Потеря связи';}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.tab){setTab(b.dataset.tab);return;}if(b.id==='scan'){scan();return;}if(b.id==='reset'){state=base();render();return;}if(b.id==='presentation'){document.body.classList.toggle('presentation');b.textContent=document.body.classList.contains('presentation')?'Вернуть дашборд':'Режим показа';return;}if(b.dataset.test){if(b.dataset.test==='offline'){state.offline=!state.offline;state.result={type:state.offline?'error':'ok',title:state.offline?'Связь отключена':'Связь восстановлена',text:state.offline?'Попробуйте сканирование. Успешное выполнение не будет показано.':'Можно продолжить сканирование.'};event(state.offline?'Демо · связь отключена':'Демо · связь восстановлена');render();}else scan(b.dataset.test);return;}if(b.dataset.digit){if(state.modal!=='manual')showModal('manual');const k=b.dataset.digit;state.manual=k==='⌫'?state.manual.slice(0,-1):k==='C'?'':state.manual+k;render();return;}const a=b.dataset.action;if(a==='back'||a==='close'){state.modal=null;render();}else if(a==='sample'){state.manual=state.tab==='receiving'&&!state.box?'BOX-0002':'2041541853067';render();}else if(a==='apply'){applyManual();}else if(a==='undo'){if(state.undo){state.count--;state.undo=false;state.result={type:'info',title:'Последнее действие отменено',text:'Счётчик сборки уменьшен на один.'};event('Сборка · отмена');render();}}else if(a==='office'||a==='warehouse'){state.zone=a==='office'?'Офис':'Склад №2';state.box=false;state.received=0;state.result=null;render();}else if(a==='finish'){state.result={type:'ok',title:'Приёмка завершена',text:state.received+' шт. принято в BOX-0002 · '+state.zone};event('Приёмка завершена · '+state.received+' шт.');state.box=false;state.received=0;render();}else if(a==='selectsupply'){state.modal=null;state.result={type:'info',title:'Поставка выбрана',text:'Поставка от 07.10.2026 готова к сборке.'};render();}else if(a==='demo'){state.modal=null;state.result={type:'info',title:'Действие показано в макете',text:'Данные остаются внутри демонстрации. На рабочий сайт ничего не отправлено.'};event('Просмотр дополнительной функции');render();}else if(a)showModal(a);});
document.addEventListener('input',e=>{if(e.target.id==='manual-input')state.manual=e.target.value.replace(/[^0-9A-Za-zА-Яа-я-]/g,'');});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)){e.preventDefault();scan();}if(e.key==='Escape'&&state.modal){state.modal=null;render();}if(e.key==='Enter'&&state.modal==='manual'){e.preventDefault();applyManual();}});
$('hardware-keys').innerHTML=['1','2','3','4','5','6','7','8','9','⌫','0','C'].map(k=>`<button data-digit="${k}" aria-label="Клавиша ${k}">${k}</button>`).join('');render();
